export const MOCK_CATALOG = [
  {
    id: "m1",
    type: "movie",
    title: "Neon Nights",
    year: 2022,
    provider: "WatchParty Original",
    url: "https://www.youtube.com/embed/ysz5S6PUM-U",
    tag: "sci-fi, synth, action",
  },
  {
    id: "m2",
    type: "movie",
    title: "Synth Samurai",
    year: 2020,
    provider: "Retro Anime",
    url: "https://www.youtube.com/embed/jfKfPfyJRdk",
    tag: "anime, cyberpunk, classic",
  },
  {
    id: "s1",
    type: "series",
    title: "Midnight MGMT",
    year: 2023,
    provider: "Cyber Series",
    url: "https://www.youtube.com/embed/ScMzIvxBSi4",
    tag: "drama, hackers",
  },
  {
    id: "s2",
    type: "series",
    title: "Streetlight Saga",
    year: 2024,
    provider: "Vibe TV",
    url: "https://www.youtube.com/embed/2Vv-BfVoq4g",
    tag: "comfort, indie",
  },
  {
    id: "a1",
    type: "anime",
    title: "Arcade Oni",
    year: 2019,
    provider: "Neon Shonen",
    url: "https://www.youtube.com/embed/kJQP7kiw5Fk",
    tag: "shonen, gaming, adventure",
  },
  {
    id: "a2",
    type: "anime",
    title: "Cloud Kintsugi",
    year: 2021,
    provider: "Sora Studio",
    url: "https://www.youtube.com/embed/tgbNymZ7vqY",
    tag: "slice of life, relaxing",
  },
];
