// src/types/voice.types.ts
import { z } from "zod";

// DTOs for voice signaling
export interface VoiceJoinDTO {
  roomId: string;
  // Optional client-provided device label
  deviceLabel?: string;
}

export interface VoiceOfferDTO {
  roomId: string;
  // SDP offer generated by the caller
  sdp: string;
}

export interface VoiceAnswerDTO {
  roomId: string;
  // SDP answer generated by the callee
  sdp: string;
}

export interface VoiceIceCandidateDTO {
  roomId: string;
  // ICE candidate string (JSON.stringify of RTCIceCandidate)
  candidate: string;
}

export interface VoiceMuteDTO {
  roomId: string;
  muted: boolean;
}

export interface VoiceStateDTO {
  roomId: string;
  // e.g., "connected", "disconnected", "connecting"
  state: string;
}

// Zod schemas for server-side validation (used by validators)
export const VoiceJoinSchema = z.object({
  roomId: z.string().min(1),
  deviceLabel: z.string().optional(),
});

export const VoiceOfferSchema = z.object({
  roomId: z.string().min(1),
  sdp: z.string().min(1),
});

export const VoiceAnswerSchema = z.object({
  roomId: z.string().min(1),
  sdp: z.string().min(1),
});

export const VoiceIceCandidateSchema = z.object({
  roomId: z.string().min(1),
  candidate: z.string().min(1),
});

export const VoiceMuteSchema = z.object({
  roomId: z.string().min(1),
  muted: z.boolean(),
});

export const VoiceStateSchema = z.object({
  roomId: z.string().min(1),
  state: z.string().min(1),
});
